#!/bin/bash
seconds_to_wait=3600
source /app/functions.sh
_SCRIPT_="$0"

ACME_BIN="/acme.sh/acme.sh --home /acme.sh --config-home /acmecerts"

DEFAULT_CONF="/etc/nginx/conf.d/default.conf"


CERTS="/etc/nginx/certs"

function update_certs {

    check_nginx_proxy_container_run || return

    [[ -f /app/letsencrypt_service_data ]] || return

    # Load relevant container settings
    unset LETSENCRYPT_CONTAINERS
    # shellcheck source=/dev/null
    source /app/letsencrypt_service_data

    should_reload_nginx='false'
    for cid in "${LETSENCRYPT_CONTAINERS[@]}"; do
        # Derive host and email variable names
        host_varname="LETSENCRYPT_${cid}_HOST"
        # Array variable indirection hack: http://stackoverflow.com/a/25880676/350221
        hosts_array="${host_varname}[@]"
        hosts_array_expanded=("${!hosts_array}")
        # First domain will be our base domain
        base_domain="${hosts_array_expanded[0]}"

        params_d_str=""
        staging=""
        email_varname="LETSENCRYPT_${cid}_EMAIL"
        email_address="${!email_varname}"
        test_certificate_varname="LETSENCRYPT_${cid}_TEST"
        dns_varname="LETSENCRYPT_${cid}_DNS"
        dns="${!dns_varname}"

        if [[ "$email_address" != "<no value>" ]]; then
            params_d_str+=" --accountemail $email_address"
        fi
        certificate_dir="/etc/nginx/certs"
        key_file_path="$certificate_dir/$base_domain.key"
        full_chain_file_path="$certificate_dir/$base_domain.crt"
        if [[ $(lc "${!test_certificate_varname:-}") == true ]]; then
            staging="--staging"
            key_file_path="$certificate_dir/test_$base_domain.key"
            full_chain_file_path="$certificate_dir/test_$base_domain.crt"
        fi

        # Create directory for the first domain and make it the cwd
        mkdir -p "$certificate_dir"
        pushd "$certificate_dir" || return

        # params_d_str+=" -d $base_domain"
        for domain in "${!hosts_array}"; do
            # Add all the domains to certificate
            params_d_str+=" -d $domain"
        done

        echo "Creating/renewal $base_domain certificates... (${hosts_array_expanded[*]})"
        $ACME_BIN $staging --issue \
          --dns $dns \
          $params_d_str \
          --days 5 \
          --fullchain-file $full_chain_file_path \
          --key-file $key_file_path \
          --reloadcmd "source /app/functions.sh && reload_nginx"
        popd || return
    done
}

update_certs

